// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"Bob","alias":"$LATEST","description":"","bot-template":"bot-import","commands-help":[],"region":"us-east-1"}],
    'aws_cognito_identity_pool_id': 'us-east-1:54542150-1cc1-4aff-bfb8-003dc845525a',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'bobapp-hosting-mobilehub-939859149',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1rtdlp1lg6ckr.cloudfront.net',
    'aws_mobile_analytics_app_id': '9acb04affe7646efa6176678d02364ff',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '0aa75adc-3c03-4ffd-9c7c-fb31b3f405c9',
    'aws_project_name': 'BobApp',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'bobapp-mobilehub-939859149',
}

export default awsmobile;
